version: '3'
services:
  www:
    build:
      context: ./
      dockerfile: Dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/core-docker-dashboard"
    environment:
      - API_URL=http://localhost:5000
    entrypoint: top -b
    logging:
      driver: none
